/** Activity type for a segment */
export type StravaActivityType = 'ride' | 'run';

/** A segment in the curated catalog */
export interface StravaSegment {
	id: number;
	name: string;
	activityType: StravaActivityType;
	polyline: string | null;
	startLatlng: [number, number];
	endLatlng: [number, number];
	distance: number;
	elevationGain: number;
	avgGrade: number;
	climbCategory: number;
	totalAttempts: number;
	totalAthletes: number;
}

/** CR/QOM record holder from React props */
export interface StravaRecordHolder {
	athleteId: number;
	athleteName: string;
	time: string;
	date: string;
	effortId: number;
	activityId: number;
}

/** A visible leaderboard row from the HTML table */
export interface StravaLeaderboardRow {
	rank: number;
	athleteName: string;
	time: string;
	speed: string | null;
	power: string | null;
	vam: string | null;
	activityId: number;
}

/** Full leaderboard data for one segment */
export interface StravaLeaderboard {
	segmentId: number;
	segmentName: string;
	cr: StravaRecordHolder | null;
	qom: StravaRecordHolder | null;
	rows: StravaLeaderboardRow[];
	totalAttempts: number;
	totalAthletes: number;
	/** Distance in meters (from segment page stats) */
	distance: number | null;
	/** Elevation gain in meters (from segment page stats) */
	elevationGain: number | null;
	/** Average grade as percentage (from segment page stats) */
	avgGrade: number | null;
	scrapedAt: string;
}

/** Change event generated by diff */
export interface StravaEvent {
	type: 'new_kom' | 'new_qom';
	segmentId: number;
	segmentName: string;
	athlete: string;
	time: string;
	effortId: number;
	activityId: number;
	previous: {
		athlete: string;
		time: string;
		effortId: number;
	} | null;
	detectedAt: string;
}

/** Top-level Blob shapes */
export interface StravaSegmentCatalog {
	segments: StravaSegment[];
	lastUpdated: string;
}

export interface StravaEventLog {
	events: StravaEvent[];
	lastUpdated: string;
}

/** Seed segment config entry (hand-curated) */
export interface StravaSeedSegment {
	id: number;
	name: string;
	activityType: StravaActivityType;
	startLatlng: [number, number];
}
